/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.54
 * Generated at: 2020-05-12 03:24:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._01_005fbasic_005fclass._2_005fform;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#frm label {\r\n");
      out.write("      display:inline-block;\r\n");
      out.write("      color:blue;\r\n");
      out.write("      width:100px;\r\n");
      out.write("}\r\n");
      out.write("#frm #addr {\r\n");
      out.write("      width:300px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h5>회원가입서 작성하기</h5>\r\n");
      out.write("\r\n");
      out.write("<form action=\"result.jsp\" method=\"get\" id=\"frm\">\r\n");
      out.write("   <div>\r\n");
      out.write("      <label for='id'>아이디</label>\r\n");
      out.write("      <input name=\"id\" type='id' id='id' placeholder='5자~10자 영어와 숫자조합' width='150'>\r\n");
      out.write("      <button>중복확인</button>\r\n");
      out.write("      <br/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <label for='password'>비밀번호</label>\r\n");
      out.write("      <input name=\"pass\" type='password' id='password' placeholder='4자이상 영어와 숫자조합' width='150'>\r\n");
      out.write("      <br/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <label for='passconf'>비밀번호확인</label>\r\n");
      out.write("      <input type='password' id='passconf' width='150'>\r\n");
      out.write("      <br/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <label for='irum'>이름</label>\r\n");
      out.write("      <input name=\"name\" type='name' id='irum' placeholder='한글 5자 이내' width='150'>\r\n");
      out.write("      <br/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <label for='phone'>전화번호</label>\r\n");
      out.write("      <input name='tel' type='tel' id='phone' placeholder='-없이 숫자조합' width='150'>\r\n");
      out.write("      <br/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <label for='addr'>주소</label>\r\n");
      out.write("      <input name='addr' type='text' id='addr' placeholder='20자 이내' width='300'>\r\n");
      out.write("      <br/>\r\n");
      out.write("   </div>\r\n");
      out.write("   <div>\r\n");
      out.write("      <label><input type='submit' id='submit' value='회원가입'></label>\r\n");
      out.write("      <input type='reset' id='reset' value='취소'>\r\n");
      out.write("      <br/>\r\n");
      out.write("   </div>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
